### PR TITLE
minimize duplicate code

### PR DESCRIPTION
**Pull request by mrmiywj**
Changelogs:
-  Change `get_object_path` return type to `Result<String, Box<Error>>`
- minimize duplicate code

---

This change is [Reviewable](https://reviewable.io/reviews/servo/devices/11)

### CODE REVIEW

**Comment by jdm** [comment]
This looks great! We just need to fix the errors that appveyor is reporting like:
```
src\bluetooth.rs:24:14: 24:35 error: type name `BluetoothAdapterBluez` is undefined or not in scope [E0412] 
src\bluetooth.rs:24     adapter: BluetoothAdapterBluez, 
                                 ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by mrmiywj** [comment]
/cc @jdm 
Sorry that I forgot to import the modules on all platform, hence it failed on windows.

**Comment by jdm** [comment]
blurz is actually linux-only, so all of those cfgs that guard uses of the crate and the types should be added back :)

**Comment by mrmiywj** [comment]
/cc @jdm 
Sorry for that I don't know blurz is linux-only. I have no access to windows platform. 
I hope for this time success!
Thank you!

**Comment by jdm** [comment]
```
src\bluetooth.rs:93:37: 93:58 error: type name `BluetoothAdapterBluez` is undefined or not in scope [E0412] 
src\bluetooth.rs:93     fn get_adapter(&self) -> Result<BluetoothAdapterBluez, Box<Error>> { 
                                                        ^~~~~~~~~~~~~~~~~~~~~ 
```
Oh. Hmm. I didn't think of this :<

**Comment by jdm** [comment]
I think we can probably define empty types (`struct BluetoothAdapterBluez`) for non-linux platforms in the same file, since they shouldn't be public.

**Comment by mrmiywj** [comment]
Yep, actually these types have no meanings on Windows platform.

But I have no Windows PC, so I cannot test it locally...  :(


发送自 Outlook Mobile






On Tue, May 3, 2016 at 12:29 PM -0700, "Josh Matthews" <notifications@github.com> wrote:












I think we can probably define empty types (struct BluetoothAdapterBluez) for non-linux platforms in the same file, since they shouldn't be public.

**Comment by mrmiywj** [comment]
/cc @jdm 
Hope success this time. QAQ
I cannot test windows platforms locally.

**Comment by jdm** [comment]
Sigh. Ok, I'll keep thinking about ways to solve this. If you have any ideas, feel free to keep changing the code and pushing to see if it makes Appveyor happy :)

**Comment by mrmiywj** [comment]
/cc @jdm 
I hope this works.
I'm afraid that if blurz has no supported functions on non-linux platforms, we have to do so.

**Comment by mrmiywj** [comment]
Sigh, this does not work. 
I'm afraid if blurz has not support for non-linux platform, we have to write redundant code.

**Comment by dati91** [comment]
AFAICT blurz won't support non-linux platform, because it is only intended to use on linux (the bluez lib is only for linux).
But if we add android (or even windows) support, the unsupported code will be reduced from half to 1/3 (or even 1/4), which is not that bad.

**Comment by mrmiywj** [comment]
Hmm, like code in what I wrote in the latest commit, just write functions used in structs implementations for those empty structs on non-linux platform. Maybe it's tricky, but I think this works

发送自我的HTC Phone

----- 回复信息 -----
发件人： "Attila Dusnoki" <notifications@github.com>
收件人： "servo/devices" <devices@noreply.github.com>
抄送： "Ivan.Yang" <jsyangwenjie@gmail.com>, "Author" <author@noreply.github.com>
主题： [servo/devices] minimize duplicate code (#11)
日期： 周三, 5月 4 日, 2016 年 16:42

AFAICT blurz won't support non-linux platform, because it is only intended to use on linux (the bluez lib is only for linux).

But if we add android (or even windows) support, the unsupported code will be reduced from half to 1/3 (or even 1/4), which is not that bad.

&mdash;You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by mrobinson** [comment]
I think this is now obsolete with changes that happened since it was posted. Sorry that this was never able to be integrated. :(

**Pull request closed without merging**
